Updates to Verifiable Presentation and Presentation Response.
microsoft/VerifiableCredential-SDK-iOS pull request #118
Opened 2022-01-25 21:54 UTC by symorton

**Problem:**
We are updating to more standard version of VC Presentation.

**Solution:**
Updated Presentation Response and Verifiable Presentation data model.
Updated POST network call to be application/json with two separate tokens instead of one.

**Validation:**
All tests pass

**Type of change:**
- [X] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

**Risk**:
- [X] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [ ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

**Work Item links**:
Please include here links for this work item, or deferred work, or related work. E.g. if the refactoring is too big to fit in this PR, or the localized strings need to be updated later, please link the TODO work items here.

**Documentation Links**:
Please include here links to any related background documentation for this PR.

2022-01-27 19:12 UTC, AndiMiko approved these changes

2022-02-10 01:04 UTC, dangodb requested changes

2022-02-10 01:04 UTC, dangodb commented on VCEntities/VCEntities/oidc/RegistrationClaims.swift
> -    public let clientPurpose: String?
Don't we need that one?

2022-02-10 01:43 UTC, symorton commented on VCEntities/VCEntities/oidc/RegistrationClaims.swift
> -    public let clientPurpose: String?
oh yes very much so

2022-02-10 18:33 UTC, dangodb approved these changes

2022-02-14 22:25 UTC, merged